"""initial_tables

Revision ID: acfd68891113
Revises: 
Create Date: 2026-02-27 01:25:31.651479

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acfd68891113'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('token_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_trail_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_user_id'), ['user_id'], unique=False)

    op.create_table('vendors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=50), nullable=True),
    sa.Column('address_zip', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_title', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('agent_company', sa.String(length=255), nullable=True),
    sa.Column('agent_email', sa.String(length=255), nullable=True),
    sa.Column('agent_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_contact_email'), ['contact_email'], unique=False)

    op.create_table('coi_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lineage_id', sa.String(length=36), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by_token_id', sa.String(length=36), nullable=True),
    sa.Column('blob_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('extraction_data', sa.JSON(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('insured_name', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('earliest_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coi_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coi_records_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coi_records_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coi_records_earliest_expiry'), ['earliest_expiry'], unique=False)
        batch_op.create_index(batch_op.f('ix_coi_records_insured_name'), ['insured_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_coi_records_lineage_id'), ['lineage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coi_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_coi_records_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('upload_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('use_limit', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_tokens_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_tokens_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_upload_tokens_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('coi_validations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coi_record_id', sa.String(length=36), nullable=False),
    sa.Column('check_name', sa.String(length=100), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=True),
    sa.Column('required_value', sa.String(length=255), nullable=True),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coi_record_id'], ['coi_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coi_validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coi_validations_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_coi_validations_coi_record_id'), ['coi_record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coi_validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coi_validations_coi_record_id'))
        batch_op.drop_index(batch_op.f('ix_coi_validations_client_id'))

    op.drop_table('coi_validations')
    with op.batch_alter_table('upload_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_tokens_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_upload_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_upload_tokens_client_id'))
        batch_op.drop_index(batch_op.f('ix_upload_tokens_building_id'))

    op.drop_table('upload_tokens')
    with op.batch_alter_table('coi_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coi_records_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_coi_records_status'))
        batch_op.drop_index(batch_op.f('ix_coi_records_lineage_id'))
        batch_op.drop_index(batch_op.f('ix_coi_records_insured_name'))
        batch_op.drop_index(batch_op.f('ix_coi_records_earliest_expiry'))
        batch_op.drop_index(batch_op.f('ix_coi_records_client_id'))
        batch_op.drop_index(batch_op.f('ix_coi_records_building_id'))

    op.drop_table('coi_records')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_contact_email'))
        batch_op.drop_index(batch_op.f('ix_vendors_company_name'))
        batch_op.drop_index(batch_op.f('ix_vendors_client_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_trail_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_client_id'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_action'))

    op.drop_table('audit_trail')
    # ### end Alembic commands ###
